# Headless service for internal access
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  ports:
  - port: 9092
    name: kafka
    targetPort: 9092
  clusterIP: None
  selector:
    app: kafka
