# Regular Service for external access
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka
    targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP
